### ISSUE TITLE
Weird character displayed in URL input box on Mac instead of placeholder

### ISSUE THREAD

**Issue by timburgess** [timburgess/brackets-pagesuck#2]
This appears to be a Mac only issue. Any dialog box using an input with class="url" receives an itinerant character in the input - usually a beta symbol. Removing class="url" from the dialog template will stop this behaviour but the input box layout is affected.

**Comment by tonyellard** [comment]
I can confirm that (assuming this is in the current version) this issue is not present on Windows.

**Comment by timburgess** [comment]
Thanks. I suspect it is a bug in the CEF 1453.1279 build on Mac. So trying a newer CEF build to see if that resolves it.
