### ISSUE TITLE
Error creating file

### ISSUE THREAD

**Issue by shaundona** [timburgess/brackets-pagesuck#4]
After trying to page suck i get an alert box pop up with the following message " An error occurred when trying to create the file BBC- Homepage.html. The target directory cannot be modified." 

Any thoughts on issue?

**Comment by timburgess** [comment]
I've pagesucked http://www.bbc.com/news/ and it has pulled down the page and named it <code>BBC News - Home.html</code> My guess is that you don't have write permissions in your current directory - which is a bit odd, but that's what the message would indicate. Try opening/saving a file in the directory where you want the pagesucked html file to be and then try the page suck.

**Comment by shaundona** [comment]
Nope sorry that solution didn't work for me :(

Same error again.

**Comment by timburgess** [comment]
The brackets API now supports creating <code>untitled</code> documents. I have created a branch that puts the content retrieved into an untitled document. Could you try this:
- On the brackets-pagesuck github page, change the branch to <code>untitle</code>
- click on the _Download ZIP_ button. This will give you a zip file named <code>brackets-pagesuck-untitle.zip</code>
- Using Brackets, find your extensions directory and copy the zip file there. Unzipping will give you a directory named <code>brackets-pagesuck-untitle</code>. Change the directory name to just <code>pagesuck</code>
- Restart Brackets and Alt-S to pagesuck.
- Let me know how it goes :-)

There is an issue with untitled files however. You can't Live Preview them. Instead you have to save them first.

**Comment by timburgess** [comment]
Untitled documents are now how the downloaded content is first held. There should be no issues with naming files as to save an untitled document goes through the normal Brackets file save process. Closing.
